/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 2882548192448d14cec7a697c97dd5e6)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	MIRROR_EMAIL: SendEmail;
	LOADER: WorkerLoader;
	IMAGES: ImagesBinding;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	EMDASH_SITE_URL: "https://repoglance.com";
	GITHUB_MIRROR_REPO: "saari-co/repoglance-site";
	MIRROR_EMAIL_FROM: "mirror@repoglance.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMDASH_SITE_URL" | "GITHUB_MIRROR_REPO" | "MIRROR_EMAIL_FROM">> {}
}
